{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nzbfast.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbfast.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- if not .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nzbfast.selectorLabels" . | nindent 6 }}
{{- end }}
