{{- if include "nzbfast.renderConfig" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config-json" (include "nzbfast.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbfast.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- include "nzbfast.configJson" . | nindent 4 }}
{{- end }}
