{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apikey" (include "nzbfast.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nzbfast.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.existingSecretKey }}: {{ .Values.apiKey.value | quote }}
{{- end }}
